version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: igreja_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/igreja_db"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
